spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_product
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-73563769.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaj89afqh2pkktA45d7
            client-secret: 1s-Qzmv38_ZlfsZahyddBq38X1--FlaKTwl8ehxcOjGZVGVwAfY5LRtuUjkBaAjr
        provider:
          okta:
            issuer-uri: https://dev-73563769.okta.com/oauth2/default

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,custom
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-73563769.okta.com/oauth2/default
    audience: api://default