server:
  port: 9090
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/v2/products/**, /api/v1/products/**, /api/v1/categories/**
          - id: category-service
            uri: lb://CATEGORY-SERVICE
            predicates:
              - Path=/api/v1/categories/**
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/users/**
          - id: rating-service
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/api/v1/ratings/**
          - id: REDIS-CACHE
            uri: lb://REDIS-CACHE
            predicates:
              - Path=/api/v1/redis/**
okta:
  oauth2:
    issuer: https://dev-73563769.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaj89afqh2pkktA45d7
    client-secret: 1s-Qzmv38_ZlfsZahyddBq38X1--FlaKTwl8ehxcOjGZVGVwAfY5LRtuUjkBaAjr
    scopes: openid, profile, email