
spring:
  application:
    name: REDIS-CACHE
  data:
    redis:
      host: redis-18490.c305.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 18490
      password: FJr3W2dcjBq6Ol68KfpiCxhAHbnk4Sj1
#  data:
#    redis:
#      host: localhost
#      port: 6379
server:
  port: 9095
okta:
  oauth2:
    issuer: https://dev-73563769.okta.com/oauth2/default
    audience: api://default
