
spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-73563769.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaj89afqh2pkktA45d7
            client-secret: 1s-Qzmv38_ZlfsZahyddBq38X1--FlaKTwl8ehxcOjGZVGVwAfY5LRtuUjkBaAjr
        provider:
            okta:
                issuer-uri: https://dev-73563769.okta.com/oauth2/default
server:
  port: 8085


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingProductCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

okta:
  oauth2:
    issuer: https://dev-73563769.okta.com/oauth2/default
    audience: api://default