spring:
  application:
    name: Rating-Service
  data:
    mongodb:
      database: ecommerce_rating
      uri: mongodb://localhost:27017

server:
  port: 8086

okta:
  oauth2:
    issuer: https://dev-73563769.okta.com/oauth2/default
    audience: api://default
