spring:
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_category
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info,custom
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8082